#!/bin/bash
set -e

cp pair_coord.py ~/mybin/pair_coord
cp pair_snps.py ~/mybin/pair_snps
cp pairviz.py ~/mybin/pairviz
cp pairviz_plot.py ~/mybin/pairviz_plot
cp loess_pairs.py ~/mybin/loess_pairs
go build pairviz_radius.go
cp pairviz_radius ~/mybin/pairviz_radius
cp pairviz_radius_plot.R ~/mybin/pairviz_radius_plot
( cd go_pairviz && go build ) && cp go_pairviz/go_pairviz ~/mybin/go_pairviz
