#!/bin/bash
set -e

pairviz_plot test_in3.bed -L chrlens.bed -N -o test_out3_log.pdf -l -p -y "FPKM proportion pairing"
pairviz_plot test_in3.bed -L chrlens.bed -N -o test_out3_nolog.pdf -p -y "FPKM proportion pairing"
