#!/bin/bash
set -e

./install

pairviz \
    -g 260000000 <(gunzip -c testdata2.pairs.gz) | \
pairviz_plot -L chrlens.bed -i -l -p -y "FPKM proportion pairing" -o test_out.pdf

pairviz \
    -g 260000000 <(gunzip -c testdata2.pairs.gz) | \
pairviz_plot -L chrlens.bed -i -l -p -y "FPKM proportion pairing" -N -o test_out3.pdf

pairviz \
    -g 260000000 <(gunzip -c testdata2.pairs.gz) -n "two" \
> test_in2.bed

pairviz \
    -g 260000000 <(gunzip -c testdata3.pairs.gz) -n "three" \
> test_in3.bed

pairviz_plot test_in3.bed test_in2.bed -L chrlens.bed -n "name" -l -p -y "FPKM proportion pairing" -o test_out2.pdf
pairviz_plot test_in3.bed test_in2.bed -L chrlens.bed -n "name" -l -p -y "FPKM proportion pairing" -X 40 -Y 5 -o test_out4.pdf
pairviz_plot test_in3.bed test_in2.bed -L chrlens.bed -n "name" -l -p -y "FPKM proportion pairing" -X 40 -Y 5 -g "line" -o test_out5.pdf
pairviz_plot test_in3.bed test_in2.bed -L chrlens.bed -n "name" -l -p -y "FPKM proportion pairing" -X 40 -Y 5 -g "line" --ylim "5,10" -o test_out6.pdf
pairviz_plot test_in3.bed -L chrlens.bed -N -o test_out3_log.pdf -l -p -y "FPKM proportion pairing"
pairviz_plot test_in3.bed -L chrlens.bed -N -o test_out3_nolog.pdf -p -y "FPKM proportion pairing"
